// VUEPROJECTS/practicavue02/src/components/ComicComponent.vue
<template>
  <div>
    <div class="card" style="width: 18rem;">
        <img :src=this.comic.imagen class="card-img-top" alt="comic">
        <div class="card-body">
            <h5 class="card-title">{{ this.comic.titulo }}</h5>
            <p class="card-text">{{ this.comic.descripcion }}</p>  
            <h3 :class="{rojo: this.comic.year <=200, verde: this.comic.year > 200}">{{this.comic.year}}</h3>      
            <button class="btn btn-success" @click="Handle_Favorito" >Favorito</button>    
            <button class="btn btn-danger" @click="Handle_Eliminar()" >Eliminar</button>   
            <router-link class="btn btn-primary" :to="'/ComicDetalles/'+this.comic.titulo" >Detalles</router-link>                
        </div>
    </div>
  </div>
</template>                .


<script>
export default {
    props: ['comic', 'index'],
    methods:{
      Handle_Favorito(){
        this.$emit("seleccionar_favorito", this.comic);
      },
      Handle_Eliminar(){
        this.$emit("delete_comic", this.index);
      }
    }
}
</script>

<style>
      @import "./../assets/Comic.css";
</style>

// ANGULARPROJECTS/ejemploangular01/src/app/Components/Comic/comic/comic.component.ts
import { query } from '@angular/animations';
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { Router } from '@angular/router';
import { Comic } from 'src/app/Models/Comic';

@Component({
  selector: 'app-comic',
  templateUrl: './comic.component.html'
})
export class ComicComponent {
  @Input() comic !: Comic; 
  @Output() eliminar: EventEmitter<Comic> = new EventEmitter<Comic>();
  @Output() favorito: EventEmitter<Comic> = new EventEmitter<Comic>();
  
  constructor(private router : Router){
  }

  Boton_Delete(){
    this.eliminar.emit(this.comic);
  }
  Boton_Favorito(){
    this.favorito.emit(this.comic);
  }
  Boton_Detalles() {
    this.router.navigate(['/comic/detalles'], 
                            { 
                              queryParams : { comic : JSON.stringify(this.comic)}
                            }
                          );
  }
  Boton_Modificar() {
    this.router.navigate(['/comic/put'], 
    { 
      queryParams : { comic : JSON.stringify(this.comic)}
    }
  );
  }
}

<div class="card " style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img [src]="comic.Get_Imagen()" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{ comic.Get_Titulo() }}</h5>
        <p class="card-text">{{ comic.Get_Descripcion() }}</p>
        <button class="btn btn-outline-primary" (click)="Boton_Modificar()">Modificar</button>
        <button class="btn btn-outline-success" (click)="Boton_Detalles()">Detalles</button>
        <button class="btn btn-outline-info" (click)="Boton_Favorito()">Favorito</button>
        <button class="btn btn-outline-danger" (click)="Boton_Delete()">Eliminar</button>
      </div>
    </div>
  </div>
</div>
