// ANGULARPROJECTS/ejemploangular01/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {
  title = 'ejemploangular01';
}

<div>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" routerLink="/">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}" >Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" routerLink="/cine" routerLinkActive="active">Cine</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" routerLink="/musica" routerLinkActive="active">Musica</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" routerLink="/doble/4" routerLinkActive="active">NumeroDoble</a>            
          </li>     
          <li class="nav-item">
            <a class="nav-link" routerLink="/collatz/4" routerLinkActive="active">Collatz</a>            
          </li>       
          <li class="nav-item">
            <a class="nav-link" routerLink="/productos" routerLinkActive="active">Productos</a>            
          </li>    
        </ul>
      </div>
    </div>
  </nav>
  
  <router-outlet></router-outlet>
</div>

// VUEPROJECTS/practicavue03/src/App.vue
<template>
  <div>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">HOME</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">           
            <li class="nav-item">
              <router-link class="nav-link" to="/tabla_multiplicar/">Tabla Multiplicar</router-link>
            </li>
            <li class="nav-item">
              <router-link class="nav-link" to="/coches_servicios/">Vue Servicios</router-link>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <router-view></router-view>
  </div>
</template>

<script>
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap";

export default {
  name: 'App',
  components: {
     
  }
}
</script>

<style>

</style>
