// VUEPROJECTS/practicavue03/src/components/Series/FormPersonaje.vue
<template>
  <div>
    <div v-if="method != undefined">
        <form v-if="method == 'post'" @submit="Submit_Personaje($event)">
            <div class="mb-3">
                <label for="Input_IdPersonaje" class="form-label">ID PERSONAJE</label>
                <input type="text" class="form-control" id="Input_IdPersonaje" aria-describedby="ID PERSONAJE">    
            </div>
            <div class="mb-3">
                <label for="Input_Nombre" class="form-label">NOMBRE</label>
                <input type="text" class="form-control" id="Input_Nombre" aria-describedby="Marca">    
            </div>
            <div class="mb-3">
                <label for="Input_Imagen" class="form-label">IMAGEN</label>
                <input type="text" class="form-control" id="Input_Imagen" aria-describedby="Modelo">    
            </div>            
            <select class="form-select text-center" aria-label="Default select example">
                <option v-for="serie in series" :key="serie" :value="serie.idSerie">     
                    {{ serie.nombre }}               
                </option>
            </select>
            <button type="submit" class="btn btn-success">Crear</button>
        </form>

        <form v-if="method == 'put'" @submit="Submit_Personaje($event)">
            <div class="mb-3">
                <label for="Input_IdPersonaje" class="form-label">ID PERSONAJE</label>
                <input type="text" class="form-control text-center" v-model="this.personaje.idPersonaje" id="Input_IdPersonaje" aria-describedby="ID PERSONAJE" disabled>    
            </div>
            <div class="mb-3">
                <label for="Input_Nombre" class="form-label">NOMBRE</label>
                <input type="text" class="form-control text-center" v-model="this.personaje.nombre" id="Input_Nombre" aria-describedby="Marca">    
            </div>
            <div class="mb-3">
                <div class="card ">
                <div class="card-header ">
                    <label for="Input_Imagen" class="form-label">IMAGEN</label>
                    <input type="text" class="form-control text-center" v-model="this.personaje.imagen" id="Input_Imagen" aria-describedby="Imagen">    
                </div>
                <div class="card-body justify-content-center">
                    <blockquote class="blockquote mb-0  h-50 w-50">
                    <img :src="this.personaje.imagen" class=" h-50 w-50">
                    </blockquote>
                </div>
            </div>
            </div>                        
            <select class="form-select text-center" aria-label="Default select example">
                <option v-for="serie in series" :key="serie" :value="serie.idSerie">     
                    {{ serie.nombre }}               
                </option>
            </select>
            <button type="submit" class="btn btn-success">Modificar</button>
        </form>

        <form v-if="method == 'detalles'">
            <div class="mb-3">
                <label for="Input_IdPersonaje" class="form-label">ID PERSONAJE</label>
                <input type="text" class="form-control text-center" v-model="this.personaje.idPersonaje" id="Input_IdPersonaje" aria-describedby="ID PERSONAJE" disabled>    
            </div>
            <div class="mb-3">
                <label for="Input_Nombre" class="form-label">NOMBRE</label>
                <input type="text" class="form-control text-center" v-model="this.personaje.nombre" id="Input_Nombre" aria-describedby="Marca">    
            </div>
            <div class="mb-3">
                <div class="card ">
                <div class="card-header ">
                    <label for="Input_Imagen" class="form-label">IMAGEN</label>
                    <input type="text" class="form-control text-center" v-model="this.personaje.imagen" id="Input_Imagen" aria-describedby="Imagen">    
                </div>
                <div class="card-body justify-content-center">
                    <blockquote class="blockquote mb-0  h-50 w-50">
                    <img :src="this.personaje.imagen" class=" h-50 w-50">
                    </blockquote>
                </div>
            </div>
            </div>                        
            <select class="form-select text-center" aria-label="Default select example">
                <option v-for="serie in series" :key="serie" :value="serie.idSerie">     
                    {{ serie.nombre }}               
                </option>
            </select>
            <button type="submit" class="btn btn-success">Modificar</button>
        </form>
  </div>
  </div>
</template>

<script>
import ServicesSeries from '../../services/ServicesSeries'
const service = new ServicesSeries();


export default {
    name: 'FormPersonaje',
    data(){
        return{
            personaje : {
                idPersonaje : null
            },
            series : [],
            method : null
        }
    },
    mounted(){
        this.personaje.idPersonaje = this.$route.params.id_personaje;        
        service.GET_Personaje(this.personaje.idPersonaje)
            .then(response=>{
                this.personaje = response.data;
            })
            .catch(error=>{
                console.log(error.message);
            });
        this.method = this.$route .params.method;
        
        service.GET_Series()
            .then(response=>{
                this.series = response.data;
            })
            .catch(error=>{
                console.log(error.message);
            });
    },
    methods:{
        Submit_Personaje(event){
            event.preventDefault();
            var form = event.target;

            this.personaje={
                idPersonaje:form[0].value,
                nombre:'',
                imagen:'',
                idSerie:''
            }
        }
    }
}
</script>

<style>

</style>

// ANGULARPROJECTS/practica_angular01/src/app/Components/form-personaje/form-personaje.component.ts
import { Component } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { Router } from '@angular/router';
import Personaje from 'src/app/Models/personaje';
import Serie from 'src/app/Models/serie';
import { SeriesService } from 'src/app/Services/series.service';

@Component({
  selector: 'app-form-personaje',
  templateUrl: './form-personaje.component.html'
})
export class FormPersonajeComponent {
  series: Array<Serie> = [];
  personaje !: Personaje;

  constructor(private serviceSeries: SeriesService , private route : Router){}

  ngOnInit(): void {
    this.Get_Series();
  }

  Get_Series(): void{
  this.series = [];
  this.serviceSeries.GET_Series().then((response: { body: Serie[]; })=>{
    response.body.forEach((serie : Serie) => {
      this.series.push(Object.assign(new Serie(), serie));
    });      
  });
  }

  Submit_Personaje(form: FormGroup<any>) {
    this.personaje = Object.assign(new Personaje(), form.value);
    this.route.navigate(['/personajes/'+ this.personaje.idSerie]);
  }

}

<form #PersonajeForm="ngForm" (submit)="Submit_Personaje(PersonajeForm.form)">
    <div formGroup="personaje">
      <div class="mb-3">
          <label for="Input_IdPersonaje" class="form-label">ID Personaje</label>
          <input type="text" class="form-control" id="Input_IdPersonaje" aria-describedby="emailHelp" ngModel name="IdPersonaje">    
        </div>
        <div class="mb-3">
          <label for="Input_Nombre" class="form-label">Nombre</label>
          <input type="text" class="form-control" id="Input_Nombre" ngModel name="nombre">
        </div>
        <div class="mb-3">
          <label for="Select_SeriePersonaje" class="form-label">Series</label>
          <select id="Select_SeriePersonaje" class="form-select" ngModel name="idSerie">
            <option *ngFor="let serie of series" [value]="serie.idSerie">
              {{serie.nombre}}
            </option>
          </select>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Crear</button>
  </form>
